### ISSUE TITLE
No visible @interface for 'VisaCheckoutButton' declares the selector 'onCheckoutWithProfile:purchaseInfo:presentingViewController:completion:'

### ISSUE THREAD

**Issue by irajwani** [entria/react-native-visa-checkout#13]
Hi,

I plan to use VISA checkout in my react native app. Right now, I am only setting up the iOS side of things. I downloaded the SDK and followed the instructions within the documentation to install the VISA checkout SDK within my app, and Ive added the react-native-visa-checkout libray to later work purely in javascript with the VISA checkout button. However, when I build my project in xcode, I get the the following error:

" No visible @interface for 'VisaCheckoutButton' declares the selector 'onCheckoutWithProfile:purchaseInfo:presentingViewController:completion:' "

This error is from the updateOnCheckout method within RNVisaCheckout.xcodeproj/RNVisaCheckoutButton.m.

Screenshot:
![screen shot 2019-01-16 at 1 47 34 pm](https://user-images.githubusercontent.com/25965881/51237059-7c6f4800-1995-11e9-925f-9a9814607745.png)

I'm checking to see if there any differences between the example app's xcodeproj that you've provided and my xcodeproj. Please help!

**Comment by sibelius** [comment]
This could be related to the visa checkout sdk version

**Comment by irajwani** [comment]
Alright, that's probably the case. However there is only one version of the iOS SDK available on [VISA docs](https://developer.visa.com/capabilities/visa_checkout/docs#adding_visa_checkout_to_a_mobile_application)

Though this seems like a completely different issue, I'm not sure about how to proceed.

**Comment by jgfidelis** [comment]
This lib is meant to be used with Visa SDK 6.2. You can try to upgrade it to the newest version and send a PR. You can test it with the Example app. Make it work with the newest version and then it should be fine.

**Comment by irajwani** [comment]
Oh very good, the SDK I have is 6.6.1. Alright, on it.

**Comment by irajwani** [comment]
The example rn app won't build on xcode. Steps taken:
1. took the example folder out of your your root project to a completely different path on my computer
2. ran npm install, got an error, so I  removed react-native-visa-checkout as a dependency, and ran npm install again, it worked. 
3. Installed react-native-visa-checkout as a dependency.
4. Ran the build in xcode after assigning a dev team, and the build failed with 20 issues. Perhaps because of third-party and glog.sh
(I'm using the legacy build system. Would you recommend against that?)

**Comment by sibelius** [comment]
post the issues and stacktrace here

third-party is a react-native problem, fixed on latest version of it

you can try to upgrade react-native version

**Comment by irajwani** [comment]
sibelius you are correct, I did not exhaust all possible solutions.

**Comment by irajwani** [comment]
Also, thank you for your help thus far. 
So I got your example app to overcome the issues mentioned earlier by upgrading the versions of react and react native. I followed the steps of integration of the iOS SDK and your example project produced the exact same error produced by my project:
![screen shot 2019-01-18 at 2 01 44 am](https://user-images.githubusercontent.com/25965881/51348723-3a452400-1ac5-11e9-8d8c-eea1da164f18.png)

To be thorough, I recorded the steps taken from the download of your repo up till this error:
1. Go to package.json and remove r-n-visa-checkout as a dependency
2. npm install --save
3. upgrade react, react native
4. Remove VisaCheckoutSDK.framework from embedded binaries and Remove RNVisaCheckout.xcodeproj from Libraries and libRNVisaCheckout.a from Link Binary with Libraries. (my mistake might have been in this step)
5. Now reinstall the r-n-visa-checkout package and move VisaCheckoutSDK.framework from the iOS SDK 6.6.1 to your example xcode project's embedded binaries section, and continue to follow the steps mentioned in your README.md and the iOS Visa Checkout SDK documentation's installation section.

Then I build my project and see the error.

**Comment by irajwani** [comment]
Okay so I redid the above WITHOUT step 4. As in, I left the .framework of the older version of the VISA Checkout SDK in embedded binaries. And I did not mess with RNVisaCheckout.xcodeproj or libRNVisaCheckout.a, AND IT WORKED, THE BUILD SUCCEEDED!!! Just waiting for the metro bundler to finish compiling to test the actual application/React Native side of things.

**Comment by sibelius** [comment]
great

feel free to upgrade this package
