### ISSUE TITLE
Remove local.properties which has hardcode paths

### ISSUE THREAD

**Issue by ovy9086** [entria/react-native-visa-checkout#4]
The local.properties file has a hardcoded path to the users SDK. I think it's best to remove it.

**Comment by sibelius** [comment]
We gonna accept a pr for this

**Comment by jgfidelis** [comment]
I think this file does not need to exist, maybe it is generated by Android studio when you open the project.

Like the name says, its where local properties stay, so its relative to its local environment, it currently has the path to the android sdk on my computer, I think we may delete it and not commit it anymore

**Comment by jgfidelis** [comment]
Just like I said, its a file generated by Android Studios, it is already in the git ignore and it is not in the repository.
